-- CURSOR
-- IMPLICIT (GÝZLÝ), EXPLICIT (AÇIK)
-- IMPLICIT CURSOR
DECLARE
  AD EMP.ENAME%TYPE;
  ID EMP.EMPNO%TYPE;
BEGIN 
  ID := 7654;
  SELECT ENAME INTO AD FROM EMP WHERE EMPNO = ID;
  
  DBMS_OUTPUT.PUT_LINE ('NUMARASI = ' || ID || ' OLAN PERSONELÝN ÝSMÝ  = ' || AD);

END;