-- CURSOR
-- IMPLICIT (GÝZLÝ), EXPLICIT (AÇIK)
-- IMPLICIT CURSOR
DECLARE
  SATIR EMP%ROWTYPE;
  ID EMP.EMPNO%TYPE;
BEGIN 
  ID := 7654;
  SELECT * INTO SATIR FROM EMP WHERE EMPNO = ID;
  
  DBMS_OUTPUT.PUT_LINE ('NUMARASI = ' || ID || ' OLAN PERSONELÝN MESLEÐÝ  = ' || SATIR.JOB);
  DBMS_OUTPUT.PUT_LINE ('NUMARASI = ' || ID || ' OLAN PERSONELÝN MAAÞI  = ' || SATIR.SAL);

END;