-- CURSOR
-- IMPLICIT (GÝZLÝ), EXPLICIT (AÇIK)
-- EXPLICIT CURSOR
DECLARE
  SATIR EMP%ROWTYPE;
  ID EMP.EMPNO%TYPE;
  M   EMP.SAL%TYPE;
  CURSOR curr IS
    SELECT * FROM EMP;
  
    
    
  ORTM EMP.SAL%TYPE;
BEGIN 
  OPEN curr;
  SELECT AVG(SAL) INTO ORTM FROM EMP;    
  DBMS_OUTPUT.PUT_LINE ('ORTALAMA MAAÞ =  ' || ORTM);  
  LOOP
    FETCH curr INTO SATIR;
    EXIT WHEN curr%NOTFOUND;
    IF (SATIR.SAL > ORTM) THEN
      DBMS_OUTPUT.PUT_LINE ('NUMARASI = ' || SATIR.EMPNO || ' OLAN PERSONELÝN MAAÞI  = ' || SATIR.SAL);
    END IF;
  END LOOP;

  

END;