--CREATE TABLE  PROD (ID NUMBER, AD VARCHAR2(32));
/*
DECLARE
  PID NUMBER;
BEGIN
  PID := 20;
  INSERT INTO PROD VALUES (PID, 'SAMSUNG');
  PID := PID + 1;
  INSERT INTO PROD VALUES (PID, 'SONY');
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('--ÝÞLEM TAMAM--');
END;
*/
SELECT * FROM PROD;