--SELECT sysdate + 5 FROM dual;
--SELECT sysdate - 5 FROM dual;
--SELECT sysdate - to_date('18/04/1974') FROM dual;
--SELECT months_between(sysdate, to_date('18/04/1974')) FROM dual;
--SELECT sysdate + 3/24 FROM dual;
--SELECT add_months(sysdate, 5) FROM dual; 
--SELECT next_day(sysdate, 'Cuma') FROM dual;
--SELECT last_day(sysdate+5) FROM dual;
--SELECT add_months(sysdate, 5), round(add_months(sysdate, 5), 'YEAR') FROM dual;
--SELECT to_char(sysdate, 'YYYY.MON.DAY') FROM dual;
--SELECT to_char(sysdate, 'DD.MM.YY') FROM dual;
--SELECT to_char(sysdate, 'DD.MM.YY-HH:MI') FROM dual;
--SELECT to_char(sysdate, 'DD.MM.YY-HH24:MI:SS') FROM dual;
--SELECT to_char(sysdate, 'SSSSS') FROM dual;
-- WW
--SELECT to_char(sysdate, 'W') FROM dual;
--SELECT to_char(sysdate, 'Q') FROM dual;
--SELECT power(2.3,3) FROM dual;
